services:
  app:
    build: .
    container_name: sre-taskmanager-app
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/taskmanager"
      REDIS_URL: "redis://redis:6379/0"
      SIMULATE_DELAY_MS: "0"
      SIMULATE_ERROR_RATE: "0.0"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: sre-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sre-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: sre-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/local-prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/local-alert-rules.yml:/etc/prometheus/alert_rules.yml:ro
    depends_on:
      - app
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: sre-alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/local-alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    container_name: sre-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/ecommerce-dashboard.json:/var/lib/grafana/dashboards/ecommerce-dashboard.json:ro
    depends_on:
      - prometheus

volumes:
  pgdata:
